In [1]:
import matplotlib.pyplot as plt
from netCDF4 import Dataset
import numpy as np

%matplotlib inline

In [2]:
df1 = Dataset('../data/grid.nc')
mask = df1['subset_flag'][:]
lat = df1['lat'][:]
lon = df1['lon'][:]
mask = np.array(mask)
lat = np.array(lat)
lon = np.array(lon)
lat = lat +.125
lon = lon + .125
land = np.where(mask==1)

In [3]:
import pandas as pd
#Train is from 2003-2011
#test is from 2012-2016
df = pd.read_pickle("../data/test.pkl")

In [4]:
df.shape

(59097600, 38)

In [8]:
land = np.array(land)
land[:,5]

array([ 26, 558])

In [10]:
df.shape

(59097600, 38)

In [12]:

hold = []
for row in range(land.shape[1]):
    i,j = land[:,row]
    temp = np.uint32(np.where(np.logical_and(df['lat']== lat[i],df['lon']==lon[j])))
    hold.append(temp)
df = df.iloc[hold]

In [9]:
np.save('../data/masked_test.npy',df)

array([ 27, 539])

In [ ]:
df = pd.read_pickle("../data/train.pkl")
hold = []
for row in range(land.shape[1]):
    i,j = land[:,row]
    temp = np.uint32(np.where(np.logical_and(df['lat']== lat[i],df['lon']==lon[j])))
    hold.append(temp)
df = df.iloc[hold]
np.save('../data/masked_train.npy',df)

In [78]:
test = np.arange(20)
test = np.reshape(test,[4,5])
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
test = pd.DataFrame(test)
test.columns = ['lat','lon','time','agb','tmx']
test

lat  lon  time  agb  tmx
0    0    1     2    3    4
1    5    6     7    8    9
2   10   11    12   13   14
3   15   16    17   18   19

In [80]:
test.loc[4]= [17,16,15,14,13]
test.loc[5]= [5,4,3,2,1]
#test.iloc[4,:] = {5,4,3,2,1}
#test.iloc[5,:] = {17,16,15,14,13}
test

lat  lon  time  agb  tmx
0    0    1     2    3    4
1    5    6     7    8    9
2   10   11    12   13   14
3   15   16    17   18   19
4   17   16    15   14   13
5    5    4     3    2    1

In [81]:
test[0]

KeyError: 0

In [82]:
test_mask = np.array([[5,6],[17,16],[10,11]])
test_mask

array([[ 5,  6],
       [17, 16],
       [10, 11]])

In [87]:

rm = []
for row in range(test_mask.shape[0]):
    # print(row)
    # print(test_mask[row])
    i,j = test_mask[row]
    # if(np.logical_and(test['lat']== i,test['lon']==j)=='True'):
    temp = int(np.where(np.logical_and(test['lat']== i,test['lon']==j))[0])
    rm.append(temp)
    # test = test.drop([np.where(np.logical_and(test['lat']== i,test['lon']==j)[0])],axis= 0)
rm
test.iloc[rm]

lat  lon  time  agb  tmx
1    5    6     7    8    9
4   17   16    15   14   13
2   10   11    12   13   14

In [76]:
test = test.drop(rm,axis=0)

In [77]:
test

lat  lon  time  agb  tmx
0    0    1     2    3    4
3   15   16    17   18   19
5    5    4     3    2    1

In [31]:
import pandas as pd
#Train is from 2003-2011
#test is from 2012-2016
df = pd.read_pickle("../data/test.pkl")
df.head()

lat     lon      time  agb  pft_fracCover  sm  pftCrop  pftHerb  \
0 -89.75 -179.75  201201.5  NaN            0.0 NaN      NaN      NaN   
1 -89.75 -179.75  201202.5  NaN            0.0 NaN      NaN      NaN   
2 -89.75 -179.75  201203.5  NaN            0.0 NaN      NaN      NaN   
3 -89.75 -179.75  201204.5  NaN            0.0 NaN      NaN      NaN   
4 -89.75 -179.75  201205.5  NaN            0.0 NaN      NaN      NaN   

   pftShrubBD  pftShrubNE  ...  dtr  pet  tmx  wet  Biome  precip  Livestock  \
0         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
1         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
2         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
3         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
4         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   

   road_density  topo  pop_density  
0           NaN   1.0          0.0  
1           NaN   1.0          0.0  
2           NaN   1.0          0.0  
3           NaN   1.0          0.0  
4           NaN   1.0          0.0  

[5 rows x 38 columns]

In [39]:
df.tail()

lat    lon      time  agb  pft_fracCover  sm  pftCrop  pftHerb  \
59097595  90.0  180.0  201605.5  NaN            0.0 NaN      NaN      NaN   
59097596  90.0  180.0  201606.5  NaN            0.0 NaN      NaN      NaN   
59097597  90.0  180.0  201607.5  NaN            0.0 NaN      NaN      NaN   
59097598  90.0  180.0  201608.5  NaN            0.0 NaN      NaN      NaN   
59097599  90.0  180.0  201609.5  NaN            0.0 NaN      NaN      NaN   

          pftShrubBD  pftShrubNE  ...  dtr  pet  tmx  wet  Biome  precip  \
59097595         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097596         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097597         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097598         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097599         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   

          Livestock  road_density  topo  pop_density  
59097595        0.0           NaN   NaN          0.0  
59097596        0.0           NaN   NaN          0.0  
59097597        0.0           NaN   NaN          0.0  
59097598        0.0           NaN   NaN          0.0  
59097599        0.0           NaN   NaN          0.0  

[5 rows x 38 columns]

In [ ]:
df.describe()

In [ ]:
df.columns

In [ ]:
df['pft_fracCover'].describe()

In [ ]:
df['pftCrop'].describe()

In [ ]:
dir(df1['subset_flag'])

In [ ]:
df1['subset_flag'].shape

In [ ]:

plt.plot(df1['subset_flag'],'.')
plt.show()

In [ ]:
df1.variables