In [30]:
import pandas as pd
import matplotlib.pyplot as plt
from netCDF4 import Dataset
import numpy as np

%matplotlib inline

In [31]:
#Train is from 2003-2011
#test is from 2012-2016
df = pd.read_pickle("../data/test.pkl")
df.head()

lat     lon      time  agb  pft_fracCover  sm  pftCrop  pftHerb  \
0 -89.75 -179.75  201201.5  NaN            0.0 NaN      NaN      NaN   
1 -89.75 -179.75  201202.5  NaN            0.0 NaN      NaN      NaN   
2 -89.75 -179.75  201203.5  NaN            0.0 NaN      NaN      NaN   
3 -89.75 -179.75  201204.5  NaN            0.0 NaN      NaN      NaN   
4 -89.75 -179.75  201205.5  NaN            0.0 NaN      NaN      NaN   

   pftShrubBD  pftShrubNE  ...  dtr  pet  tmx  wet  Biome  precip  Livestock  \
0         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
1         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
2         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
3         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
4         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   

   road_density  topo  pop_density  
0           NaN   1.0          0.0  
1           NaN   1.0          0.0  
2           NaN   1.0          0.0  
3           NaN   1.0          0.0  
4           NaN   1.0          0.0  

[5 rows x 38 columns]

In [39]:
df.tail()

lat    lon      time  agb  pft_fracCover  sm  pftCrop  pftHerb  \
59097595  90.0  180.0  201605.5  NaN            0.0 NaN      NaN      NaN   
59097596  90.0  180.0  201606.5  NaN            0.0 NaN      NaN      NaN   
59097597  90.0  180.0  201607.5  NaN            0.0 NaN      NaN      NaN   
59097598  90.0  180.0  201608.5  NaN            0.0 NaN      NaN      NaN   
59097599  90.0  180.0  201609.5  NaN            0.0 NaN      NaN      NaN   

          pftShrubBD  pftShrubNE  ...  dtr  pet  tmx  wet  Biome  precip  \
59097595         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097596         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097597         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097598         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097599         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   

          Livestock  road_density  topo  pop_density  
59097595        0.0           NaN   NaN          0.0  
59097596        0.0           NaN   NaN          0.0  
59097597        0.0           NaN   NaN          0.0  
59097598        0.0           NaN   NaN          0.0  
59097599        0.0           NaN   NaN          0.0  

[5 rows x 38 columns]

In [ ]:
df.describe()

In [ ]:
df.columns

In [ ]:
df['pft_fracCover'].describe()

In [ ]:
df['pftCrop'].describe()

In [3]:
df1 = Dataset('../Data/grid.nc')

In [5]:
land = df1['subset_flag'][:]
lat = df1['lat'][:]
lon = df1['lon'][:]
land = np.array(land)
lat = np.array(lat)
lon = np.array(lon)

In [6]:
lat = lat+.125

In [7]:
lon = lon+.125

In [10]:
ocean = np.where(land==0)

In [13]:
ocean

(array([  0,   0,   0, ..., 719, 719, 719]),
 array([   0,    1,    2, ..., 1437, 1438, 1439]))

In [14]:
land.shape

(720, 1440)

In [15]:
lat.shape

(720,)

In [25]:
ocean = np.array(ocean)
ocean.shape

(2, 792557)

In [28]:
ocean[:,79255]

array([ 62, 898])

In [18]:
ocean_coords = np.array(lat[0])

TypeError: tuple indices must be integers or slices, not tuple

In [53]:
test.size

AttributeError: 'tuple' object has no attribute 'size'

In [ ]:
df1 = pd.DataFrame(df1['subset_flag'])

In [ ]:
dir(df1['subset_flag'])

In [ ]:
df1['subset_flag'].shape

In [ ]:

plt.plot(df1['subset_flag'],'.')
plt.show()

In [ ]:
df1.variables