In [11]:

from netCDF4 import Dataset
import numpy as np
#from multiprocessing import Pool

In [12]:
df1 = Dataset('../data/grid.nc')
mask = df1['subset_flag'][:]
lat = df1['lat'][:]
lon = df1['lon'][:]
mask = np.array(mask)
lat = np.array(lat)
lon = np.array(lon)
lat = lat +.125
lon = lon + .125
land = np.where(mask==1)

In [16]:
arr = np.load('../data/test_0.npy')
test = np.array(np.shape(land)[1])

array(2)

In [17]:
test.shape

()

In [13]:
land = np.array(land).T
type(land)

numpy.ndarray

In [15]:
tup1 = np.array(lat[land[:,0]])
tup2 = np.array(lon[land[:,1]])
land_coords = np.column_stack((tup1,tup2))

In [18]:
land_coords[:5,:]

array([[ 83.75, -34.25],
       [ 83.75, -34.  ],
       [ 83.75, -33.75],
       [ 83.5 , -40.75],
       [ 83.5 , -40.5 ]])

In [ ]:
indices = np.arange(14400)
temp = np.zeros((land_coords.shape[0],arr.shape[1]))
for i in indices:
    hor = arr[i*57][0]
    ver = arr[i*57][1]
    if np.all(np.logical_and((hor==land_coords[:,0]),(ver==land_coords[:,1])))==False:


In [ ]:
test = np.arange(20)
test = np.reshape(test,[4,5])
test = np.row_stack((test,[17,16,15,14,13]))
test = np.row_stack((test,[5,4,3,2,1]))
land = np.array([[5,6],[17,16],[10,11]])
temp = np.zeros((land.shape[0],test.shape[1]))
c = 0
for index in range(test.shape[1]):
    lat = test[index][0]
    lon = test[index][1]
    print(np.logical_and((lat==land[:,0]),(lon==land[:,1])))
    if np.any(np.logical_and((lat==land[:,0]),(lon==land[:,1])))==True:
        temp[c] = test[index]
        c+=1
temp

numpy.ndarray

In [14]:
land[0:5,1]

array([582, 583, 584, 556, 557])

In [20]:
arr[0][0]


-89.75

In [14]:
244243/720/1440

0.2355738811728395

: 

In [4]:
import pandas as pd
#Train is from 2003-2011
#test is from 2012-2016
df = pd.read_pickle("../data/train.pkl")

In [5]:
df.shape

(111974400, 38)

In [8]:
land = np.array(land)
land[:,5]

array([ 26, 558])

In [10]:
df.shape

(59097600, 38)

In [12]:

hold = []
for row in range(land.shape[1]):
    i,j = land[:,row]
    temp = np.uint32(np.where(np.logical_and(df['lat']== lat[i],df['lon']==lon[j])))
    hold.append(temp)
df = df.iloc[hold]

ValueError: Buffer has wrong number of dimensions (expected 1, got 3)

In [ ]:
np.save('../data/masked_test.npy',df)

array([ 27, 539])

In [ ]:
df = pd.read_pickle("../data/train.pkl")
hold = []
for row in range(land.shape[1]):
    i,j = land[:,row]
    temp = np.uint32(np.where(np.logical_and(df['lat']== lat[i],df['lon']==lon[j])))
    hold.append(temp)
df = df.iloc[hold]
np.save('../data/masked_train.npy',df)

In [6]:
111974400/1440/720

108.0

In [7]:
720*1440

1036800

In [8]:
144*57

8208

In [9]:
144*108

15552

In [1]:
import pandas as pd 
import numpy as np
test = np.arange(20)
test = np.reshape(test,[4,5])
test = np.row_stack((test,[17,16,15,14,13]))
test = np.row_stack((test,[5,4,3,2,1]))

In [5]:
land = np.array([[5,6],[17,16],[10,11]])
land.shape[0]

3

In [9]:
land = np.array([[5,6],[17,16],[10,11]])
temp = np.zeros((land.shape[0],test.shape[1]))
c = 0
for index in range(test.shape[1]):
    lat = test[index][0]
    lon = test[index][1]
    print(np.logical_and((lat==land[:,0]),(lon==land[:,1])))
    if np.any(np.logical_and((lat==land[:,0]),(lon==land[:,1])))==True:
        temp[c] = test[index]
        c+=1
temp

[False False False]
[ True False False]
[False False  True]
[False False False]
[False  True False]


array([[ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [17., 16., 15., 14., 13.]])

In [10]:
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [17, 16, 15, 14, 13],
       [ 5,  4,  3,  2,  1]])

In [82]:
test_mask = np.array([[5,6],[17,16],[10,11]])
test_mask

array([[ 5,  6],
       [17, 16],
       [10, 11]])

In [87]:

rm = []
for row in range(test_mask.shape[0]):
    # print(row)
    # print(test_mask[row])
    i,j = test_mask[row]
    # if(np.logical_and(test['lat']== i,test['lon']==j)=='True'):
    temp = int(np.where(np.logical_and(test['lat']== i,test['lon']==j))[0])
    rm.append(temp)
    # test = test.drop([np.where(np.logical_and(test['lat']== i,test['lon']==j)[0])],axis= 0)
rm
test.iloc[rm]

lat  lon  time  agb  tmx
1    5    6     7    8    9
4   17   16    15   14   13
2   10   11    12   13   14

In [76]:
test = test.drop(rm,axis=0)

In [77]:
test

lat  lon  time  agb  tmx
0    0    1     2    3    4
3   15   16    17   18   19
5    5    4     3    2    1

In [1]:
import pandas as pd
#Train is from 2003-2011
#test is from 2012-2016
df = pd.read_pickle("../data/test.pkl")
df.head()

lat     lon      time  agb  pft_fracCover  sm  pftCrop  pftHerb  \
0 -89.75 -179.75  201201.5  NaN            0.0 NaN      NaN      NaN   
1 -89.75 -179.75  201202.5  NaN            0.0 NaN      NaN      NaN   
2 -89.75 -179.75  201203.5  NaN            0.0 NaN      NaN      NaN   
3 -89.75 -179.75  201204.5  NaN            0.0 NaN      NaN      NaN   
4 -89.75 -179.75  201205.5  NaN            0.0 NaN      NaN      NaN   

   pftShrubBD  pftShrubNE  ...  dtr  pet  tmx  wet  Biome  precip  Livestock  \
0         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
1         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
2         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
3         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   
4         NaN         NaN  ...  NaN  NaN  NaN  NaN   99.0     NaN        0.0   

   road_density  topo  pop_density  
0           NaN   1.0          0.0  
1           NaN   1.0          0.0  
2           NaN   1.0          0.0  
3           NaN   1.0          0.0  
4           NaN   1.0          0.0  

[5 rows x 38 columns]

In [39]:
df.tail()

lat    lon      time  agb  pft_fracCover  sm  pftCrop  pftHerb  \
59097595  90.0  180.0  201605.5  NaN            0.0 NaN      NaN      NaN   
59097596  90.0  180.0  201606.5  NaN            0.0 NaN      NaN      NaN   
59097597  90.0  180.0  201607.5  NaN            0.0 NaN      NaN      NaN   
59097598  90.0  180.0  201608.5  NaN            0.0 NaN      NaN      NaN   
59097599  90.0  180.0  201609.5  NaN            0.0 NaN      NaN      NaN   

          pftShrubBD  pftShrubNE  ...  dtr  pet  tmx  wet  Biome  precip  \
59097595         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097596         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097597         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097598         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   
59097599         NaN         NaN  ...  NaN  NaN  NaN  NaN    0.0     NaN   

          Livestock  road_density  topo  pop_density  
59097595        0.0           NaN   NaN          0.0  
59097596        0.0           NaN   NaN          0.0  
59097597        0.0           NaN   NaN          0.0  
59097598        0.0           NaN   NaN          0.0  
59097599        0.0           NaN   NaN          0.0  

[5 rows x 38 columns]

In [ ]:
df.describe()

In [2]:
df.columns

Index(['lat', 'lon', 'time', 'agb', 'pft_fracCover', 'sm', 'pftCrop',
       'pftHerb', 'pftShrubBD', 'pftShrubNE', 'pftTreeBD', 'pftTreeBE',
       'pftTreeND', 'pftTreeNE', 'GDP', 'ign', 'Distance_to_populated_areas',
       'fPAR', 'LAI', 'NLDI', 'vod_K_anomalies', 'FPAR_12mon', 'LAI_12mon',
       'Vod_k_anomaly_12mon', 'FPAR_06mon', 'LAI_06mon', 'Vod_k_anomaly_06mon',
       'WDPA_fracCover', 'dtr', 'pet', 'tmx', 'wet', 'Biome', 'precip',
       'Livestock', 'road_density', 'topo', 'pop_density'],
      dtype='object')

In [ ]:
df['pft_fracCover'].describe()

In [ ]:
df['pftCrop'].describe()

In [ ]:
dir(df1['subset_flag'])

In [ ]:
df1['subset_flag'].shape

In [ ]:

plt.plot(df1['subset_flag'],'.')
plt.show()

In [ ]:
df1.variables

In [1]:
59097600/1440/720

57.0

In [3]:
7/23

0.30434782608695654

Creating file with land co-ordinates and saving it inside data

In [18]:
df1 = Dataset('../data/grid.nc')
mask = df1['subset_flag'][:]
lat = df1['lat'][:]
lon = df1['lon'][:]
mask = np.array(mask)
lat = np.array(lat)
lon = np.array(lon)
lat = lat +.125
lon = lon + .125
land = np.where(mask==1)
land = np.array(land).T
tup1 = np.array(lat[land[:,0]])
tup2 = np.array(lon[land[:,1]])
land_coords = np.column_stack((tup1,tup2))
np.save('../data/land_coords.npy',land_coords)

In [6]:
import numpy as np

land = np.load('../data/land_coords.npy')
land[0]

array([ 83.75, -34.25])

In [7]:
land.shape

(244243, 2)

In [1]:
import numpy as np
test = np.load("../data/test_sans_ocean.npy")

In [12]:
test[0:57,0]

array([-55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75, -55.75,
       -55.75])

In [3]:
#Check for structural integrity, but I am immensely tired, so that is  that
#bootstarrping, bagging, bayesian, stacking
#Not a kill me moment, but this is what I am signing up for, 
#Causality, Bayesian, and no money what on Earth am I Thinking
#Best part, I am thinking, still sticking to it
#Good luck to me, ig
#The only way out is by being the next David Silver
#He has Silver in his name, how did I not see this abhi tak

In [4]:
test.shape

(13921851, 38)

In [15]:
flag = True
place = -1
for i in range(test.shape[0]//57):
    lat = test[i*57:(i+1)*57,0]
    lon = test[i*57:(i+1)*57,1]
    _,c = np.unique(lat,return_counts=True)
    if(c==57):
        _,c = np.unique(lat,return_counts=True)
        if(c!=57):
            flag = False
            place = i
            break
    else:
        flag = False
        place = i
        break
print(flag)
print(place)
    

True
-1


In [16]:
import gc
del(test)
gc.collect()

1270

In [ ]:
test = np.load("../data/train_sans_ocean.npy")

In [21]:

for i in range(test.shape[0]//108):
    lat = test[i*108:(i+1)*108,0]
    lon = test[i*108:(i+1)*108,1]
    _,c = np.unique(lat,return_counts=True)
    if(c==108):
        _,c = np.unique(lat,return_counts=True)
        if(c!=108):
            flag = False
            place = i
            break
    else:
        flag = False
        place = i
        break
print(flag)
print(place)

True
-1


In [25]:
test[0,0:2]

array([-55.75, -67.  ])

In [26]:
time_step = 108
coord_train = np.zeros((test.shape[0]//time_step,2))
for i in range(test.shape[0]//time_step):
    coord_train[i]=test[i*time_step,0:2]
np.save('../data/coord_train.npy',coord_train)
del(test)
gc.collect()

1996

In [27]:
test = np.load("../data/test_sans_ocean.npy")

In [28]:
time_step = 57
coord_test = np.zeros((test.shape[0]//time_step,2))
for i in range(test.shape[0]//time_step):
    coord_test[i]=test[i*time_step,0:2]
np.save('../data/coord_test.npy',coord_test)
del(test)
gc.collect()

11