In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
    #0: 34 Livestock
    #1: 35 road_density
    #2: 37 pop_density
    #3: 14 GDP

In [2]:
import joblib

In [3]:
road_density =  joblib.load("../output/feature1.joblib")

In [4]:
from sklearn import tree
fn = ['lat 0', 'lon 1', 'agb 3', 'pft_fracCover 4', 'sm 5', 'pftCrop 6',
       'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9', 'pftTreeBD 10', 'pftTreeBE 11',
       'pftTreeND 12', 'pftTreeNE 13', 'Distance_to_populated_areas 16',
       'fPAR 17', 'vod_K_anomalies 20', 'WDPA_fracCover 27', 'dtr 28', 
       'pet 29', 'tmx 30', 'wet 31', 'Biome 32', 'precip 33']
cn = ['ign']

['lat 0', 'lon 1', 'time 2', 'agb 3', 'pft_fracCover 4', 'sm 5', 'pftCrop 6',
       'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9', 'pftTreeBD 10', 'pftTreeBE 11',
       'pftTreeND 12', 'pftTreeNE 13', 'GDP 14', 'ign 15', 'Distance_to_populated_areas 16',
       'fPAR 17', 'LAI 18', 'NLDI 19', 'vod_K_anomalies 20', 'FPAR_12mon 21', 'LAI_12mon 22',
       'Vod_k_anomaly_12mon 23', 'FPAR_06mon 24', 'LAI_06mon 25', 'Vod_k_anomaly_06mon 26',
       'WDPA_fracCover 27', 'dtr 28', 'pet 29', 'tmx 30', 'wet 31', 'Biome 32', 'precip 33',
       'Livestock 34', 'road_density 35', 'topo 36', 'pop_density 37']
np.delete(x_train,[2,14,15,18,19,21,22,23,24,25,26,34,35,36,37],axis = 1)
['lat 0', 'lon 1', 'agb 3', 'pft_fracCover 4', 'sm 5', 'pftCrop 6',
       'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9', 'pftTreeBD 10', 'pftTreeBE 11',
       'pftTreeND 12', 'pftTreeNE 13', 'Distance_to_populated_areas 16',
       'fPAR 17', 'vod_K_anomalies 20', 'WDPA_fracCover 27', 'dtr 28', 
       'pet 29', 'tmx 30', 'wet 31', 'Biome 32', 'precip 33']

In [6]:
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=800)
tree.plot_tree(road_density.estimators_[0],
               filled = True)
fig.suptitle('Road Density + Base Model')
plt.show()
plt.close()

KeyboardInterrupt: 

In [ ]:
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=800)
tree.plot_tree(road_density.estimators_[0],
               feature_names = fn, 
               class_names=cn,
               filled = True)
fig.suptitle('Road Density + Base Model')
plt.show()


In [ ]:
plt.close()

In [1]:
import numpy as np
train = np.load('../../data/train_sans_ocean.npy')
train.shape

(26378244, 38)

In [2]:
ign = train[:,15]

In [3]:
np.nan_to_num(ign, copy =False, nan =0)

array([0., 0., 0., ..., 0., 0., 0.])

In [4]:
ign = np.where(train[:,15]==0)
no_ign = np.nonzero(train[:,15])


In [7]:
ign[0].shape

(25037988,)

In [5]:
no_ign[0].shape

(1340256,)

In [8]:
no_ign[0].shape

(1340256,)

In [2]:
ign = np.where(train[:,15]==0)
no_ign = np.nonzero(train[:,15])

#ign_train  = train_x[ign]
#no_ign_train = train_x[no_ign]

ign[0].shape

(0,)

In [3]:
no_ign[0].shape

(26378244,)

In [13]:
ign[0].shape[0]/no_ign[0].shape[0]

18.68149666929303

In [9]:
noign = np.where(train[:,15]!=0)
no_ign[0].shape[0]

1340256

In [ ]:
new_no_ign = train[np.random.choice(no_ign[0],ign[0].shape,replace = False)]
new_ign = train[np.random.choice(ign[0],ign[0].shape[0],replace = False)]
x_train = np.stack((new_ign,new_no_ign),axis = 1)
np.random.shuffle(x_train)

In [19]:
inds[0].shape[0]

25037988

In [9]:
inds_no = np.where(train[:,15]!=0)

In [11]:
len(inds)

1

In [16]:
train[[0,1]]

array([[-5.57500000e+01, -6.70000000e+01,  2.00301500e+05,
         2.20695457e+01,  1.56014338e-01,  0.00000000e+00,
         3.70377791e-04,  3.57659161e-02,  1.48828998e-02,
         0.00000000e+00,  1.03704989e-01,  1.22224691e-03,
         0.00000000e+00,  0.00000000e+00,  1.91550547e+04,
         0.00000000e+00,  0.00000000e+00,  7.19999969e-01,
         2.00000000e+00,  1.00999999e+00,  0.00000000e+00,
         7.19999969e-01,  2.00000000e+00,  0.00000000e+00,
         7.19999969e-01,  2.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  6.50000000e+00,  2.20000005e+00,
         1.06999998e+01,  1.60799999e+01,  0.00000000e+00,
         1.20339996e+02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-5.57500000e+01, -6.70000000e+01,  2.00302500e+05,
         2.20695457e+01,  1.56014338e-01,  0.00000000e+00,
         3.70377791e-04,  3.57659161e-02,  1.48828998e-02,
         0.00000000e+00,  1.03704989e-01,  1.22224691e-03,
         0.00

In [34]:
ign = 10
no_ign = 15
x = lambda ign: ign if ign>no_ign else no_ign

In [38]:
x(ign)

15

In [ ]:
f = lambda x,y: x if x>y else y,x

In [8]:
temp = np.arange(30)
temp = np.reshape(temp,(3,2,5))
temp[0][0]

array([0, 1, 2, 3, 4])

In [5]:
temp.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [2]:
import numpy as np

In [3]:
train_x = np.load("../../data/train_monthmean.npy")
train_x.shape[-1]

38

In [14]:
train_x = train_x.reshape(-1,38)

In [15]:
train_x.shape

(26378244, 38)

In [17]:
np.any(np.count_nonzero(train_x[:,2]))

True

In [5]:
"""
Balancing the dataset because RF is really sensitive to it
"""
no_ign = np.where(train_x[:,15]==0)
ign = np.nonzero(train_x[:,15])

#ign_train  = train_x[ign]
#no_ign_train = train_x[no_ign]
"""I have absolutely no idea why ign is larger than no ign and if I should run the model or not"""

new_no_ign = train_x[np.random.choice(no_ign[0],ign[0].shape,replace = False)]
new_ign = train_x[np.random.choice(ign[0],ign[0].shape[0],replace = False)]

IndexError: index 15 is out of bounds for axis 1 with size 9

In [3]:
train_x.shape

(26378244, 38)

In [4]:
new_ign.shape

(1340256, 38)

In [11]:
x_train = np.concatenate((new_ign,new_no_ign),axis = 0)

In [12]:
x_train.shape

(2680512, 38)

In [8]:
new_no_ign.shape

(1340256, 38)

In [18]:
arr = np.arange(30)
arr = np.reshape(arr, (2,3,5))
arr


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [27]:
arr[0,:]

array([0, 1, 2, 3, 4])

In [25]:
arr = np.reshape(arr,(6,5))

In [28]:
arr[0,:]

array([0, 1, 2, 3, 4])