In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
    #0: 34 Livestock
    #1: 35 road_density
    #2: 37 pop_density
    #3: 14 GDP

In [2]:
import joblib

In [3]:
road_density =  joblib.load("../output/feature1.joblib")

In [4]:
from sklearn import tree
fn = ['lat 0', 'lon 1', 'agb 3', 'pft_fracCover 4', 'sm 5', 'pftCrop 6',
       'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9', 'pftTreeBD 10', 'pftTreeBE 11',
       'pftTreeND 12', 'pftTreeNE 13', 'Distance_to_populated_areas 16',
       'fPAR 17', 'vod_K_anomalies 20', 'WDPA_fracCover 27', 'dtr 28', 
       'pet 29', 'tmx 30', 'wet 31', 'Biome 32', 'precip 33']
cn = ['ign']

['lat 0', 'lon 1', 'time 2', 'agb 3', 'pft_fracCover 4', 'sm 5', 'pftCrop 6',
       'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9', 'pftTreeBD 10', 'pftTreeBE 11',
       'pftTreeND 12', 'pftTreeNE 13', 'GDP 14', 'ign 15', 'Distance_to_populated_areas 16',
       'fPAR 17', 'LAI 18', 'NLDI 19', 'vod_K_anomalies 20', 'FPAR_12mon 21', 'LAI_12mon 22',
       'Vod_k_anomaly_12mon 23', 'FPAR_06mon 24', 'LAI_06mon 25', 'Vod_k_anomaly_06mon 26',
       'WDPA_fracCover 27', 'dtr 28', 'pet 29', 'tmx 30', 'wet 31', 'Biome 32', 'precip 33',
       'Livestock 34', 'road_density 35', 'topo 36', 'pop_density 37']
np.delete(x_train,[2,14,15,18,19,21,22,23,24,25,26,34,35,36,37],axis = 1)
['lat 0', 'lon 1', 'agb 3', 'pft_fracCover 4', 'sm 5', 'pftCrop 6',
       'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9', 'pftTreeBD 10', 'pftTreeBE 11',
       'pftTreeND 12', 'pftTreeNE 13', 'Distance_to_populated_areas 16',
       'fPAR 17', 'vod_K_anomalies 20', 'WDPA_fracCover 27', 'dtr 28', 
       'pet 29', 'tmx 30', 'wet 31', 'Biome 32', 'precip 33']

In [6]:
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=800)
tree.plot_tree(road_density.estimators_[0],
               filled = True)
fig.suptitle('Road Density + Base Model')
plt.show()
plt.close()

KeyboardInterrupt: 

In [ ]:
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=800)
tree.plot_tree(road_density.estimators_[0],
               feature_names = fn, 
               class_names=cn,
               filled = True)
fig.suptitle('Road Density + Base Model')
plt.show()


In [ ]:
plt.close()

In [1]:
import numpy as np
train = np.load('../../data/train_sans_ocean.npy')
train.shape

(26378244, 38)

In [2]:
ign = train[:,15]

In [3]:
np.nan_to_num(ign, copy =False, nan =0)

array([0., 0., 0., ..., 0., 0., 0.])

In [4]:
ign = np.where(train[:,15]==0)
no_ign = np.nonzero(train[:,15])


In [7]:
ign[0].shape

(25037988,)

In [5]:
no_ign[0].shape

(1340256,)

In [8]:
no_ign[0].shape

(1340256,)

In [2]:
ign = np.where(train[:,15]==0)
no_ign = np.nonzero(train[:,15])

#ign_train  = train_x[ign]
#no_ign_train = train_x[no_ign]

ign[0].shape

(0,)

In [3]:
no_ign[0].shape

(26378244,)

In [13]:
ign[0].shape[0]/no_ign[0].shape[0]

18.68149666929303

In [9]:
noign = np.where(train[:,15]!=0)
no_ign[0].shape[0]

1340256

In [ ]:
new_no_ign = train[np.random.choice(no_ign[0],ign[0].shape,replace = False)]
new_ign = train[np.random.choice(ign[0],ign[0].shape[0],replace = False)]
x_train = np.stack((new_ign,new_no_ign),axis = 1)
np.random.shuffle(x_train)

In [19]:
inds[0].shape[0]

25037988

In [9]:
inds_no = np.where(train[:,15]!=0)

In [11]:
len(inds)

1

In [16]:
train[[0,1]]

array([[-5.57500000e+01, -6.70000000e+01,  2.00301500e+05,
         2.20695457e+01,  1.56014338e-01,  0.00000000e+00,
         3.70377791e-04,  3.57659161e-02,  1.48828998e-02,
         0.00000000e+00,  1.03704989e-01,  1.22224691e-03,
         0.00000000e+00,  0.00000000e+00,  1.91550547e+04,
         0.00000000e+00,  0.00000000e+00,  7.19999969e-01,
         2.00000000e+00,  1.00999999e+00,  0.00000000e+00,
         7.19999969e-01,  2.00000000e+00,  0.00000000e+00,
         7.19999969e-01,  2.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  6.50000000e+00,  2.20000005e+00,
         1.06999998e+01,  1.60799999e+01,  0.00000000e+00,
         1.20339996e+02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-5.57500000e+01, -6.70000000e+01,  2.00302500e+05,
         2.20695457e+01,  1.56014338e-01,  0.00000000e+00,
         3.70377791e-04,  3.57659161e-02,  1.48828998e-02,
         0.00000000e+00,  1.03704989e-01,  1.22224691e-03,
         0.00

In [34]:
ign = 10
no_ign = 15
x = lambda ign: ign if ign>no_ign else no_ign

In [38]:
x(ign)

15

In [ ]:
f = lambda x,y: x if x>y else y,x

In [8]:
temp = np.arange(30)
temp = np.reshape(temp,(3,2,5))
temp[0][0]

array([0, 1, 2, 3, 4])

In [5]:
temp.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [2]:
import numpy as np

In [3]:
train_x = np.load("../../data/train_monthmean.npy")
train_x.shape[-1]

38

In [14]:
train_x = train_x.reshape(-1,38)

In [15]:
train_x.shape

(26378244, 38)

In [17]:
np.any(np.count_nonzero(train_x[:,2]))

True

In [5]:
"""
Balancing the dataset because RF is really sensitive to it
"""
no_ign = np.where(train_x[:,15]==0)
ign = np.nonzero(train_x[:,15])

#ign_train  = train_x[ign]
#no_ign_train = train_x[no_ign]
"""I have absolutely no idea why ign is larger than no ign and if I should run the model or not"""

new_no_ign = train_x[np.random.choice(no_ign[0],ign[0].shape,replace = False)]
new_ign = train_x[np.random.choice(ign[0],ign[0].shape[0],replace = False)]

IndexError: index 15 is out of bounds for axis 1 with size 9

In [3]:
train_x.shape

(26378244, 38)

In [4]:
new_ign.shape

(1340256, 38)

In [11]:
x_train = np.concatenate((new_ign,new_no_ign),axis = 0)

In [12]:
x_train.shape

(2680512, 38)

In [8]:
new_no_ign.shape

(1340256, 38)

In [18]:
arr = np.arange(30)
arr = np.reshape(arr, (2,3,5))
arr


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [27]:
arr[0,:]

array([0, 1, 2, 3, 4])

In [25]:
arr = np.reshape(arr,(6,5))

In [28]:
arr[0,:]

array([0, 1, 2, 3, 4])

In [1]:
import numpy as np
train_x = np.load("../../data/train_zeros.npy")

"""
Balancing the dataset because RF is really sensitive to it
"""


'\nBalancing the dataset because RF is really sensitive to it\n'

In [2]:
train_x.shape

(26378244, 38)

In [3]:
no_ign = np.where(train_x[:,15]==0)
ign = np.nonzero(train_x[:,15])
new_no_ign = train_x[np.random.choice(no_ign[0],ign[0].shape,replace = False)]
new_ign = train_x[np.random.choice(ign[0],ign[0].shape[0],replace = False)]
x_train = np.concatenate((new_ign,new_no_ign),axis = 0)
x_train.shape

(2680512, 38)

In [4]:
np.random.shuffle(x_train)
x_train.shape

(2680512, 38)

In [5]:
train_y = x_train[:,15].copy()
x_train = np.delete(x_train,[2,15,18,19,21,22,23,24,25,26,36],axis = 1)
x_train.shape

(2680512, 27)

In [6]:
x_train = np.delete(x_train,[13,24,25,26],axis = 1)
x_train.shape

(2680512, 23)

In [2]:
import numpy as np
x_train = np.load("../../data/zeros_balanced.npy")


In [3]:
x_train.shape

(2680512, 38)

In [4]:
x_train = np.delete(x_train,[0,1,2,15,18,19,21,22,23,24,25,26,32,36],axis = 1)#Train with the economic factors
x_train.shape

(2680512, 24)

In [6]:
x_train = np.delete(x_train,[3,11,12,15,21,22,23],axis = 1)


In [7]:
x_train.shape

(2680512, 17)

| Old | New | Economic Factors|
| --- | ----------- | --------- |
| lat 0 | - |
| lon 1 | - |
| time 2 | - |
| agb 3 | 0 |
| pft_fracCover 4 | 1 |
| sm 5 | 2 |
| pftCrop 6 | 3 | True |
| pftHerb 7 | 4 |
| pftShrubBD 8 | 5 |
| pftShrubNE 9 | 6 |
| pftTreeBD 10 | 7 |
| pftTreeBE 11 | 8 |
| pftTreeND 12 | 9 |
| pftTreeNE 13 | 10 |
| GDP 14 | 11 | True |
| ign 15 | - |
| Distance_to_populated_areas 16 | 12 | True |
| fPAR 17 | 13 |
| LAI 18 | - |
| NLDI 19 | - |
| vod_K_anomalies 20 | 14 |
| FPAR_12mon 21 | - |
| LAI_12mon 22 | - |
| Vod_k_anomaly_12mon 23 | - |
| FPAR_06mon 24 | - |
| LAI_06mon 25 | - |
| Vod_k_anomaly_06mon 26 | - |
| WDPA_fracCover 27 | 15 | True |
| dtr 28 | 16 |
| pet 29 | 17 |
| tmx 30 | 18 |
| wet 31 | 19 |
| Biome 32 | - |
| precip 33 | 20 |
| Livestock 34 | 21 | True |
| road_density 35 | 22 | True |
| topo 36 | - |
| pop_density 37| 23 | True |


pftCrop 3, GDP 11, Distance_to_populated_areas 12, WDPA_fracCover15, livestock 22, road_density 23, pop_density 24

In [1]:
import numpy as np
x_test  = np.load('../../data/test_monthmean.npy')

In [2]:
x_test.shape

(244243, 5, 12, 38)

In [3]:
new_x = x_test.reshape((x_test.shape[0],-1,x_test.shape[-1]))

In [4]:
new_x.shape

(244243, 60, 38)

In [5]:
new_x = np.delete(new_x,(57,58,59),axis = 1)
new_x.shape

(244243, 57, 38)

In [6]:
x_test = np.reshape(new_x,(-1,38))
x_test.shape

(13921851, 38)

In [7]:
import joblib
x_test = np.delete(x_test,[0,1,2,15,18,19,21,22,23,24,25,26,32,36],axis = 1)
model = joblib.load('../../output/month_mean/feature_all.joblib')

/home/npande/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [8]:
y_pred = model.predict(x_test)
y_pred_mean = np.mean(np.reshape(y_pred,(-1,57)),axis = 1)

In [9]:
y_pred_mean.shape

(244243,)

In [ ]:
x = np.linspace(-89.5,90,720)
y = np.linspace(-179.5,180,1440)
lons,lats = np.meshgrid(y,x)
grid = np.zeros((720,1440))
y_pred_mean = np.reshape(y_pred_mean,(-1,1))
y_pred_mean = np.append(lon.reshape(-1,1),y_pred_mean,axis = 1)#lon
y_pred_mean = np.append(lat.reshape(-1,1),y_pred_mean,axis = 1)#lat
for i in range(y_pred_mean.shape[0]):
    grid[int(y_pred_mean[:,0][i]+89.5)*4][int(y_pred_mean[:,1][i]+179.5)*4] = y_pred_mean[:,2][i]
fig = plt.figure(figsize=(35,30), edgecolor='w')
map = Basemap(projection='cyl',resolution='c',llcrnrlat=-90,urcrnrlat=90,llcrnrlon=-180,urcrnrlon=180)
map.pcolormesh(lons,lats,grid,cmap = 'plasma')
map.drawcoastlines(color='lightgray')
map.drawparallels(np.arange(-90.,91.,15.),color='grey')
map.drawmeridians(np.arange(-180.,181.,30.),color='grey')
plt.title(" Predicted Ignitions - all")
plt.colorbar()
plt.savefig('../output/month_mean/all')
plt.close()
del(model)
gc.collect()

In [1]:
import numpy as np
x_test  = np.load('../../data/test_monthmean.npy')
x_test = x_test.reshape((x_test.shape[0],-1,x_test.shape[-1]))
x_test = np.delete(x_test,(57,58,59),axis = 1)
x_test = x_test.reshape((-1,38))
y_test = np.copy(x_test[:,15])

In [2]:

echoes = x_test[:,[6,14,16,27,34,35,37]].copy()
space_time = np.copy(x_test[:,[0,1,2]])


In [4]:
echoes.shape

(13921851, 7)

In [5]:
space_time.shape

(13921851, 3)

In [2]:
import numpy as np
nmse = np.load('../../output/month_mean/err_all_none.npy')
nmse

array([0, 0, 0, 1])

In [11]:
mean_err = np.load('../../output/zeros/err_mean.npy')
mean_err


array([[4.49140382],
       [4.12411109],
       [4.5824738 ],
       [4.56954992],
       [4.23056604],
       [4.50833409],
       [4.53426178]])

pftCrop, GDP, Distance to populated areas, WDPA_frac_Cover, Livestock, road_density, pop_density

In [12]:
err_all = np.load('../../output/zeros/err_all_none.npy')#all_nmse,all_mean, none_nmse,none_mean
err_all

array([0, 3, 0, 4])