<br>This file will split the train and test into 72 files each.
<br> The files are of npy format for easier I/O and smaller sizes 
<br> Each file contains 14400 points with 57 time steps for train and 108 timesteps for test 

In [1]:
from multiprocessing import Pool
from itertools import repeat
import numpy as np
import gc

In [2]:
def split(index,step):
    np.save('../data/test_%s.npy'%index,arr[index*1440*step:((index+1)*1440*step)-1])

In [3]:

if __name__ == '__main__':
    indices = np.arange(72)
    global arr
    arr = np.load('../data/test.pkl', allow_pickle='True')
    step = arr.shape[0]/720/1440
    with Pool() as p:
        p.starmap(split,zip(indices,repeat(step)))
        p.close()
        p.join()
    del(arr)
    gc.collect()
    arr = np.load('../data/train.pkl', allow_pickle='True')
    step = arr.shape[0]/720/1440
    with Pool() as p:
        p.starmap(split,zip(indices,repeat(step)))
        p.close()
        p.join()
    del(arr)
    gc.collect()



TypeError: cannot do slice indexing on RangeIndex with these indexers [492480.0] of type float64

In [5]:
492480//14400

34

In [3]:
from multiprocessing import Pool
import numpy as np
import gc
def split_train(index):
    step = int(arr.shape[0]/720/1440)
    np.save('../data/train_%s.npy'%index,arr[index*14400*step:((index+1)*14400*step)])
arr = np.load('../data/train.pkl', allow_pickle='True')

In [4]:
indices = np.arange(72)
with Pool() as p:
    p.map(split_train,indices)
p.close()
p.join()
del(arr)
gc.collect()

0

In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr_new = np.append(arr,np.transpose([[5,6,7]]),axis = 1)

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr_new

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 7]])

In [20]:
arr_newer = np.append(arr,arr[:,[0,2]],axis = 1)

In [18]:
arr[:,2].shape

(3,)

In [21]:
arr_newer

array([[1, 2, 3, 1, 3],
       [4, 5, 6, 4, 6],
       [7, 8, 9, 7, 9]])

In [24]:
testing = arr_newer[:,[0,2,4]]

In [28]:
test_arr = np.append(arr,np.transpose([testing[1]]),axis = 1)

In [26]:
testing[1].shape

(3,)