In [35]:
import numpy as np
arr = np.load('../../data/custom_median.npy')
arr[arr==-9999.0] = 0
np.save('../../data/custom_median.npy',arr)
arr.shape

(26378244, 30)

In [39]:
np.any(arr==-9999)

False

In [38]:
np.set_printoptions(suppress=True)
arr[0]

array([   -55.75      ,    -67.        , 200301.5       ,      0.        ,
            2.54603505,      0.        ,      0.00037038,      0.03576592,
            0.0148829 ,      0.        ,      0.10370499,      0.00122225,
            0.        ,      0.        ,  19155.0546875 ,      0.        ,
            0.71999997,      2.        ,      0.        ,      0.        ,
            2.20000005,     16.07999992,    115.63246918,      0.        ,
            0.        ,  -9999.        ,      0.        ,      6.5       ,
           10.69999981,      0.        ])

In [2]:
col = np.load('../../data/column_names.npy')
col

array(['lat 0', 'lon 1', 'time 2', 'road_density 3', 'agb 4', 'sm 5',
       'pftCrop 6', 'pftHerb 7', 'pftShrubBD 8', 'pftShrubNE 9',
       'pftTreeBD 10', 'pftTreeBE 11', 'pftTreeND 12', 'pftTreeNE 13',
       'GDP_per_capita_PPP 14', 'ign 15', 'faPAR 16', 'LAI 17',
       'vod_K_anomalies 18', 'primn 19', 'pet 20', 'wet 21', 'precip 22',
       'pastr 23', 'Band1 24', 'pop_density 25',
       'Distance_to_populated_areas 26', 'Diurnal temperature range 27',
       'temp_max 28', 'Livestock 29'], dtype='<U30')

In [17]:
gfed = np.load('../../data/gfed_regions.npy',allow_pickle=True)
gfed

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [15]:
gfed

{'ign': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'lat': array([[ 89.875,  89.875,  89.875, ...,  89.875,  89.875,  89.875],
        [ 89.625,  89.625,  89.625, ...,  89.625,  89.625,  89.625],
        [ 89.375,  89.375,  89.375, ...,  89.375,  89.375,  89.375],
        ...,
        [-89.375, -89.375, -89.375, ..., -89.375, -89.375, -89.375],
        [-89.625, -89.625, -89.625, ..., -89.625, -89.625, -89.625],
        [-89.875, -89.875, -89.875, ..., -89.875, -89.875, -89.875]],
       dtype=float32),
 'lon': array([[-179.875, -179.625, -179.375, ...,  179.375,  179.625,  179.875],
        [-179.875, -179.625, -179.375, ...,  179.375,  179.625,  179.875],
        [-179.875, -179.625, -179.375, ...,  179.375,  179.625,  179.875],
        ...,
        [-179.875, -179.625, -179.375, ...,  179.375,  179.625, 

In [18]:
shaf = np.where(gfed==9)
seas = np.where(gfed==12)
boas = np.where(gfed==10)
aust = np.where(gfed==14)
euro = np.where(gfed==6)

In [19]:
shaf

(array([360, 360, 360, ..., 499, 499, 499]),
 array([757, 758, 759, ..., 798, 799, 800]))

In [20]:
lat = np.arange(90,-90,-0.25)
lon = np.arange(-180, 180, 0.25)

In [21]:
lat.shape

(720,)

In [22]:
shaf_lat = lat[shaf[0]]
shaf_lon = lon[shaf[1]]

In [43]:
shaf_lat.max()

0.0

In [27]:
idxs = (arr[:,0]>=shaf_lat.min())and(arr[:,0]<=shaf_lat.max())and(arr[:,1]>=shaf_lon.min())and(arr[:,1]<=shaf_lon.max())

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:


# boolean index to filter rows where column 2 values are greater or equal to k
#idxs = (arr[:,0]>=shaf_lat.min())and(arr[:,0]<=shaf_lat.max())and(arr[:,1]>=shaf_lon.min())and(arr[:,1]<=shaf_lon.max())
arr_shaf = arr[arr[:, 0] >= shaf_lat.min()]
arr_shaf = arr_shaf[arr_shaf[:, 0] <= shaf_lat.max()]
arr_shaf = arr_shaf[arr_shaf[:, 1] >= shaf_lon.min()]
arr_shaf = arr_shaf[arr_shaf[:, 1] <= shaf_lon.max()]
arr_shaf = arr_shaf[:,[0,1,6,8,14,15,16,22,25,26,28]]
dim = np.vstack((shaf_lat,shaf_lon))


In [45]:
arr_shaf.shape

(1426248, 11)

In [61]:
shaf_val = []
for i in range(dim.shape[1]):
    mask = np.all(arr_shaf[:, :2] == dim[:,i], axis=1)
    if np.any(mask)==True:
        shaf_val.append(arr_shaf[mask])  


In [62]:
len(shaf_val)

13126

In [64]:
shaf_lat.shape[0]-len(shaf_val)

510

In [59]:
mask = np.all(arr_shaf[:, :2] == dim[:,1], axis=1)

In [60]:
np.any(mask)

True

In [50]:
shaf_val = np.array(shaf_val)
shaf_val.shape

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (13636,) + inhomogeneous part.

In [10]:

np.save('../../data/shaf.npy',shaf_val)

In [22]:
arr_shaf.shape[0]/108

94448.0

In [12]:
arr_shaf.shape[0]/arr.shape[0]

0.38669685518111063

In [13]:
import pandas as pd
df = pd.DataFrame(arr_shaf,columns=['lat','lon','pftCrop','pftShrub','GDP','ign','fapar','precip','pop_density','distance2pop','temp_max'])

In [14]:
hold = []
for i in range(shaf_lat.shape[0]):
    lat,lon = shaf_lat[i],shaf_lon[i]
    temp = (np.where(np.logical_and(df['lat']== lat,df['lon']==lon)))
    hold.append(temp)
df_shaf = df.iloc[hold]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (13636, 1) + inhomogeneous part.

In [59]:
hold

[(array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=int64),),
 (array([], dtype=in

In [29]:
dim = np.vstack((lat,lon))
shaf_val = np.array([]) 
for i in dim:
    mask = np.all(arr_shaf[:, :2] == i, axis=1)
    shaf_val = np.append(arr_shaf,arr_shaf[mask],axis=0)   
shaf_val.shape[0]

10200384

In [38]:
len(hold)

13636

In [37]:
shaf_val.shape[0]-10199728

656

In [39]:
shaf_val.shape

(10200384, 11)

In [40]:
np.save('../../data/shaf.npy',shaf_val,)

In [27]:
import numpy as np

# create sample arrays
dim = np.array([[3, 2],
                [5, 7],
                [1, 8]])
data = np.array([[1, 2, 3, 4],
                 [3, 2, 5, 6],
                 [5, 7, 8, 9],
                 [3, 2, 10, 11],
                 [1, 8, 12, 13],
                 [1, 2, 14, 15]])

# extract the first two columns from data
data_cols_12 = data[:, :2]

# create a boolean mask for rows where the first two columns match dim
mask = np.all(data_cols_12 == dim, axis=1)

# use the boolean mask to select the rows from data
selected_rows = data[mask]

print(selected_rows)




/tmp/ipykernel_139689/2683765984.py:18: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  mask = np.all(data_cols_12 == dim, axis=1)


AxisError: axis 1 is out of bounds for array of dimension 0

In [27]:
df_shaf = df.iloc[hold[1]]

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [40]:
import numpy as np

# create sample arrays
dim = np.array([[3, 2],
                [5, 7],
                [1, 8]])
data = np.array([[1, 2, 3, 4],
                 [3, 2, 5, 6],
                 [5, 7, 8, 9],
                 [3, 2, 10, 11],
                 [1, 8, 12, 13],
                 [1, 2, 14, 15]])

# extract the first two columns from data
data_cols_12 = data[:, :2]

# create a boolean mask for rows where the first two columns match dim
mask = np.all(data_cols_12 == dim, axis=1)

# use the boolean mask to select the rows from data
selected_rows = data[mask]

print(selected_rows)


/tmp/ipykernel_265394/1163514368.py:18: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  mask = np.all(data_cols_12 == dim, axis=1)


AxisError: axis 1 is out of bounds for array of dimension 0

In [41]:
data_cols_12 == dim

/tmp/ipykernel_265394/1031744749.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  data_cols_12 == dim


False

In [ ]:
data_cols_12 == dim_broadcasted[:, np.newaxis]